### ISSUE TITLE
Support page endpoint in url

### ISSUE THREAD

**Issue by klihelp** [michaelbromley/ngx-pagination#147]
**Description of issue**: 
Support page number in url.

**Angular version**: 
4

**ngx-pagination version**: 
3

**Comment by michaelbromley** [comment]
Hi, could you elaborate a bit on what you mean?

**Comment by klihelp** [comment]
How can I see page changes in the url?
How can I share the second page with the url?

**Comment by michaelbromley** [comment]
Ah I see. This is beyond the scope of this library, but you can use the `pageChanged()` method to update a parameter in the url via the Angular Router. Your component would also have to read that parameter on init in order to set the value of `currentPage`, which would allow you to share the url to a particular page.

If you need more detailed help, I suggest you try StackOverflow.
