### ISSUE TITLE
ngx-pagination net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by McNairy** [michaelbromley/ngx-pagination#159]
**Angular version**: 4.0.0

**ngx-pagination version**: 3.0.0

**Description of issue**:
Get "ngx-pagination net::ERR_FILE_NOT_FOUND" in Chrome developer tools.
**Steps to reproduce**:
Follow installation instructions and simple example.

**Expected result**:
Pager.

**Actual result**:
No pager.

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
In order to get it to work I added the following line to the map section of my systemjs.config.ts
```
'ngx-pagination': 'npm:ngx-pagination/dist/ngx-pagination.umd.js'

```

**Comment by michaelbromley** [comment]
Hi,

I don't think you should be using the UMD bundle if you are using system.js. If you take a look at the system.js config on the [plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) (see config.js), you'll see how I did it there.

**Comment by McNairy** [comment]
Thanks for the response and thanks for an awesome module! Unfortunately, I don't know any better (I'm a week into learning Angular) so I just added that lined there since I saw Angular Material puts several UMD bundles in the system.js file. At my current skill level looking at your config.js example hurts my brain. I'll keep looking it over to learn from it, but really I just wanted to plug it in like any other module and was letting you know what I had to do in order to do that. Thanks again for all the work you put into this.

**Comment by michaelbromley** [comment]
Okay, a week into learning Angular is not long - I can appreciate that there are a whole bunch of new and daunting things to wrap your head around all at once!

I'm not an expert when it comes to system.js - I don't use it in any of my own projects - but from what I understand it is able to load ES modules (i.e. files which use the `import` and `export` keywords), and from setting up the Plunker demo it seems this is the case. 

So to simplify, maybe if you just use:

```
'ngx-pagination': 'npm:ngx-pagination'
```
in your config it would work. I'm not sure, so check it out and see.

Otherwise you might have more luck on StackOverflow.
