### ISSUE TITLE
Error in PaginationControlsComponent: No provider for PaginationService

### ISSUE THREAD

**Issue by jpralle** [michaelbromley/ngx-pagination#168]
**Angular version**: 2.4.10

Also using angular-cli, so jsut to be sure: ng -v
angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
angular/common: 2.4.10
angular/compiler: 2.4.10
angular/core: 2.4.10
angular/forms: 2.4.10
angular/http: 2.4.10
angular/platform-browser: 2.4.10
angular/platform-browser-dynamic: 2.4.10
angular/router: 3.4.10
angular/cli: 1.0.0-rc.1
angular/compiler-cli: 2.4.10
angular/language-service: 4.1.3

**ngx-pagination version**: 3.0.0

**Description of issue**: I used the simple from your docs, but it tells me that there is no provider for PaginationService in PaginationControlsComponent. I just pasted your code, splitted the template into a seperate files (both attached), went over to my module file and added the imports
import {NgxPaginationModule} from 'ngx-pagination';
import {PaginationService} from 'ngx-pagination';
  imports: [
    [...]
    NgxPaginationModule
  ]

put the new component into the declarations
  declarations: [
    [...]
    DocumentResultListPagination,
  ]
and provided the service
  providers: [
   [...]
    PaginationService
  ],

The provision of the service was not in your code, but I tried it after the error appeared. No change though. Here's what the console of my browser says:
EXCEPTION: Error in ./PaginationControlsComponent class PaginationControlsComponent - inline template:1:4 caused by: No provider for PaginationService!
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:338
Zone.runTask @ zone.js:169
ZoneTask.invoke @ zone.js:420

[document-result-list-pagination.zip](https://github.com/michaelbromley/ngx-pagination/files/1071619/document-result-list-pagination.zip)

**Steps to reproduce**: Not sure if there's something in the above information missing.

**Expected result**: No error :) The integration for now is just very basic, to see if it generally works, so it should show your simple example with the list entries of 1 to 13.

**Actual result**: Above error message and nothing shown in the browser window.

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork): I will try to make one, if the above information is not enough, though I think it will be very hard, as Plunker is not using angular-cli, I think. Please let me know when it's needed.

Any relevant code: 

[document-result-list-pagination.zip](https://github.com/michaelbromley/ngx-pagination/files/1071619/document-result-list-pagination.zip)

**Comment by michaelbromley** [comment]
Hi,

So the error message means that the injector for the component `DocumentResultListPagination` does not know about the `PaginationService`. There are 2 ways the injector would know about it:

1) It is provided at the module level. This seems to be what you are doing when you import `NgxPaginationModule` into your app module. If the `DocumentResultListPagination` component belongs to that module then the injector should know about the PaginationService.
2) It can also be provided to the component directly or one of it's ancestors by using the `providers: []`  array in the `@Component` decorator.

From your code, it looks like at the module level you are both importing `NgxPaginationModule` *and* providing the `PaginationService`. The latter is not needed, since by importing the module, the PaginationService is implicitly being provided to your app module.

I'm not sure if that is the reason who you get the error though. I have just recently created an Angular CLI project and used this module without issue, so there must be something else wrong which I cannot see from the information provided so far.

**Comment by jpralle** [comment]
Hi,

thanks for the info. I already feared that you wouldn't answer, thus we already moved to other topics in our project, but I will put it back on our angenda. That's also the reason why I didn't reply earlier. We will check on it and if it does not work, we will come back to you.

**Comment by michaelbromley** [comment]
Hi, I'm closing this as it has been inactive for a while. If you find that you still need help, let me know and I can re-open.
