### ISSUE TITLE
Holding Pagination State/Page # When User Navigates Away and Returns

### ISSUE THREAD

**Issue by darrenbrett** [michaelbromley/ngx-pagination#174]
Hi Michael,

Thanks, ngx-pagination is working really well in my app. Just wanted to get your feedback on caching, or, more specifically, how to handle this situation: Data is first loaded to a page (page 1 on first load). Then the user clicks through to page 3 of those paginated results. Then the user opens a new tab of unrelated data. Currently, in my app, when they then return to the first tab (i.e. make it the active tab again), I'm back to page 1 for that data, rather than page 3, where the user last left off. Any ideas on the simplest way to hold the current pagination state in that kind of scenario?

**Comment by michaelbromley** [comment]
Hi Darren,

I would recommend you use the router to store the current page in the URL. I've used this in my own apps and it works well - back/forward navigation just works as you would expect.

The general idea is to have a param, say `page` and then in your component you subscribe to this param and use it to update the `currentPage` value in the pagination config. When you change page, rather than directly updating `currentPage`, you just use the router to navigate to the URL with that page as the `page` param. Your subscription will then automatically handle the update.

Roughly:

```TypeScript
class MyComponent {
  config = {
    currentPage: 1,
    itemsPerPage: 10
  };
  constructor(private router: Router, private route: ActivatedRoute) {}

  ngOnInit() {
    this.route.paramMap
      .map(params => params.get('page'))
      .subscribe(page => this.config.currentPage = page);
  }

  pageChange(newPage: number) {
    this.router.navigate(['path/to/here'], { queryParams: { page: newPage } });
  }
}
```

**Comment by darrenbrett** [comment]
Perfect. I will give that a go. Thanks!

**Comment by bitbeter** [comment]
when i @michaelbromley solution, the current page style in pagination isn't change,(changing color of current page to blue)

**Comment by michaelbromley** [comment]
@bitbeter Hi, the styling issue would be a separate issue you can open if you like.

I'll close this one as it seems resolved.
