### ISSUE TITLE
Please tell us new version of ngx-pagination.

### ISSUE THREAD

**Issue by 02harleen** [michaelbromley/ngx-pagination#181]
**Angular version**:^4.3.3

**ngx-pagination version**:^3.0.1

**Description of issue**: Please tell us a new version.

**Comment by michaelbromley** [comment]
Hi,

I don't understand what the issue is. Please clarify.

**Comment by flycat52** [comment]
I'm using Angular 4 as well. 
**@angular/common@~4.3.1
@angular/core@~4.3.1**

When I tried to install ngx-pagination version:^3.0.1, it gets below warning so that pagination component cannot be installed.

npm WARN ngx-pagination@3.0.1 requires a peer of @angular/core@>=2.3.1 but none was installed.
npm WARN ngx-pagination@3.0.1 requires a peer of @angular/common@>=2.3.1 but none was installed.

Do you have an updated ngx-pagination version specific for Angular 4?

**Comment by flycat52** [comment]
Thanks, I changed the angular version to 4.3.5 then it's successful.
