### ISSUE TITLE
Pagination State 

### ISSUE THREAD

**Issue by jtan80813** [michaelbromley/ngx-pagination#226]
Hi. Could you help me solve this issue? [https://stackoverflow.com/questions/48217600/redirect-to-previous-page-in-angular]. Its all about the pagination state problem. Thanks.

**Comment by michaelbromley** [comment]
Hi,

This is a support request, and indeed StackOverflow is the correct place for this. This issue tracker is specifically for bugs and feature requests and the like.

Unfortunately I don't have time to personally field support requests. But the answers you are getting are along the right track - store the currentPage state in the URL. This has the bonus of making the back/forward buttons work with the paging too.

**Comment by jtan80813** [comment]
Hi Michael. The problem is how can on the router params. I cant transfer or click a certain page.

**Comment by michaelbromley** [comment]
Again, this is a support request. As I explained, I have minimal time to help on these kind of requests.

However, in order to help improve you chances of getting help with requests like these, always try to provide:

1) A complete, unambiguous description of the problem you are trying to solve. *"The problem is how can on the router params. I cant transfer or click a certain page."* - this is inadequate for me to even understand what you are trying to do. If you have poor English skills, I'm afraid this might just be tough, but it is essential nonetheless.

2) **IMPORTANT** detail what you have tried so far which didn't work. People are much more willing to donate their time to someone who comes across as being sincerely stuck rather than simply lazy. Ideally include a reproduction of your issue and at the minimum show the code you have already written in an attempt to solve the issue. 

3) If you are truly clueless as to where to begin with solving the issue, just say so. In this case, I would personally say "do some tutorials about Angular and the router and then try to solve it yourself". Lacking this key information, well intentioned people can get unwittingly sucked into protracted round of hand-holding through every subsequent suggestion or instruction. This can make them resentful towards helping strangers in the future.

For my part, I try to encourage these points by including an [issue template](https://github.com/michaelbromley/ngx-pagination/issues/new) which you saw when you opened this issue originally. In this case, you deleted it without filling out any of the pertinent information or heeding its advice. In future, try to read and follow such templates. They help keep OSS maintainers sane and help you get your issues resolved faster.

I know I have absolutely not answered your last message directly, but I hope this is useful advice nonetheless.

**Comment by jtan80813** [comment]
I’m sorry. I have the link above to my problem in stackoverflow and i really need your help since the problem is that i can able to click the page. Lets say flr example localhost:4200/books?page=3. BUT the problem is that i cant be redirected to the page 3 of the books list. But i can see the url changing. Please see the link i have provided above. I have shown the code to my link. Thanks Michael
