### ISSUE TITLE
cannot use it with index, on the other pages index restart to 0

### ISSUE THREAD

**Issue by Pescu** [michaelbromley/ngx-pagination#252]
**Angular version**: 4.2.4

**ngx-pagination version**:3.1.1

**Description of issue**:cannot use it with index, on the other pages index restart to 0

**Steps to reproduce**:create table with 2 pages, the index on the second page restart from 0

**Expected result**:max item per page + current page index

**Actual result**:current page index

Any relevant code:
```

 <ul>
         <li *ngFor="let item of [1, 2, 3] | paginate: { id:'test', itemsPerPage: 2, currentPage: p }; let i = index">{{ i }}</li>
</ul>
<pagination-controls id="test" (pageChange)="p = $event"></pagination-controls>

```
with a list of items = ['item', 'item', 'item']
i get:
i = 0,
i = 1,

next page
i = 0, instead of i = 2

What could be the problem?

**Comment by Pescu** [comment]
I resolve the problem replacing the i with i + (p - 1) * 2(itemsPerPage)
But i think this should be done in automatically.
Is this a bug? Or its the normal way of use?

**Comment by michaelbromley** [comment]
Hi,

You did it right. It's not a bug - it's just that `ngFor` has no knowledge of the pagination and therefore the value of `index` is always relative to the current page only.

Since this question comes up from time to time I just added a [section to the FAQ](https://github.com/michaelbromley/ngx-pagination/blob/master/README.md#how-do-i-get-the-absolute-index-of-a-list-item) about it.
