### ISSUE TITLE
ERROR CONTEXT <failed to convert exception to string>

### ISSUE THREAD

**Issue by alandroid** [michaelbromley/ngx-pagination#255]
**Angular version**:
^5.2.9

**ngx-pagination version**:
^3.0.1

**Description of issue**:
Interaction with pagination custom template produces error or does not work as expected.

**Steps to reproduce**:
Click any control in custom template.

**Expected result**:
Pagination

**Actual result**:
(pageChange)="p = $event" --- `Uncaught Error: Cannot assign to a reference or variable!`
(pageChange)="p.setCurrent($event)" --- `ERROR CONTEXT <failed to convert exception to string>`
(pageChange)="pageChange.emit($event)" --- Nothing happens, pagination does not occur...

**Any relevant code:**
```
@Output() pageChange = new EventEmitter<number>();

{ itemsPerPage: 10, currentPage: 1, id: 'test1' }
<pagination-template #p="paginationApi" [id]="'test1'" (pageChange)="pageChange.emit($event)">
```

Help very appreciated.

**Comment by michaelbromley** [comment]
Hi,

When you set `currentPage: 1` in the pipe arguments, you should instead use a variable, otherwise you are essentially hard-coding the fact that the current page can only ever be 1.

I also notice that you are assigning the `paginationApi` to the template variable `p`. If that is the case, then use another variable name to represent the current page, e.g. `currentPage`. Then you should be able to do: `(pageChange)="currentPage = $event"`.

**Comment by alandroid** [comment]
Thank you for you help Michael, great library, works great!
