### ISSUE TITLE
Need new methods in "paginationApi" while using <pagination-template>

### ISSUE THREAD

**Issue by ksatyaprakash** [michaelbromley/ngx-pagination#258]
Hi Team,

Is it possble to provide new methods (**pApi.getTotalItems()**, **pApi.getItemsPerPage()**) from **paginationApi**.

Scenario (using angular 5):
- Sample screenshot
![image](https://user-images.githubusercontent.com/23015836/41517718-a6aa4cbc-72da-11e8-8221-70301c379588.png)
![image](https://user-images.githubusercontent.com/23015836/41518128-0a20a464-72de-11e8-82f6-6d55ca66d86b.png)
![image](https://user-images.githubusercontent.com/23015836/41518173-58c73b28-72de-11e8-86c1-59118dfbe8d5.png) **(with filterBy)**

- Using with data filter, inside "**pagination-template**", to display "**Displaying 1 - 12 of 63**" along with number of pages

- Sample Code:
`<tr
 *ngFor="let row of dataCollection | filterBy: searchText | orderBy:{ property: sortBy, direction: reverse } | paginate: { itemsPerPage: itemsPerPage, currentPage: p }; let i = index" class="cald_tr_cells">`
.....
`<pagination-template #pApi="paginationApi" [id]="custom" (pageChange)="p = $event"><div class="range-label" style="padding-top: 5px;padding-left: 5px;">Displaying {{(( p > 1 ? p : 1 ) - 1) * pApi.getItemsPerPage() + 1}} - {{(( ( p > 1 ? p : 1 ) - 1) * pApi.getItemsPerPage()) + pApi.getItemsPerPage() > pApi.getTotalItems() ? pApi.getTotalItems() : ((( p > 1 ? p : 1 ) - 1) * pApi.getItemsPerPage()) + pApi.getItemsPerPage()}} of {{ pApi.getTotalItems() }}</div> <!-- some code to design pages --></pagination-template>`

Regards,
Satya

**Comment by michaelbromley** [comment]
Hi Satya,

Thanks for the suggestions. I wonder whether the proposed `pApi.getItemsPerPage()` is really needed, since this information is readily available since it is defined by the user config. If the motivation for adding this API so that the `itemsPerPage` value does not need to be explicitly passed down to the custom template?

Regarding the `pApi.getTotalItems()` method, this is certainly something that is not easily achievable currently in the case of things like a filter pipe which changes the size of the set (see #166, #99).

In the case of an array of items which is being filtered by some custom pipe prior to pagination, the total length is already being stored internally in the `PaginationInstance` ([see here](https://github.com/michaelbromley/ngx-pagination/blob/737cc1611ae3ceb7150e6aad5efed67b10ba0a54/src/paginate.pipe.ts#L87)) so this could be exposed in the `PaginationControlsDirective` with a method like:

```TypeScript
getTotalItems(): number {
  return this.service.getInstance(this.id).totalItems
}
```

BTW, If you feel inclined to submit a pull request for this, let me know. Otherwise I will mark it to add in a future update.

**Comment by ksatyaprakash** [comment]
Thanks Michael,

Yes, we don't need **`pApi.getItemsPerPage()`**, we already know what is the page size.

Please provide this feature **`pApi.getTotalItems()`** in you next release.

Thanks & Regards,
Satya
