### ISSUE TITLE
Server side pagination with custom template

### ISSUE THREAD

**Issue by sahil1989** [michaelbromley/ngx-pagination#261]
I cannot find any example where server side pagination is implemented with a custom template. Could someone guide me for the same

**Comment by michaelbromley** [comment]
Hi,

This looks like a general support request rather than an issue specifically related to this project. Unfortunately I don't have time to field such requests, and a better source of assistance would be [StackOverflow](http://stackoverflow.com/).

If you think I've made a mistake and this is indeed an issue specific to this project, please re-open the issue and include further detail.
