### ISSUE TITLE
Pagination with Django Rest Framework

### ISSUE THREAD

**Issue by arikbidny** [michaelbromley/ngx-pagination#269]
Hey, 
Im trying to implement this solution for my angular and django rest api project, 
The issue that my django rest does the work of pagination and passes 3 things to front:
count, next ( url ), previous ( url )
I dont want to pass all the data because its to many data. 
What the right way to implement this approach ? 
thanks for help..

=======

**Angular version**: 6 

**ngx-pagination version**: latest

**Description of issue**: ngx-pagination with django

**Comment by michaelbromley** [comment]
Hi,

Please see the section on [server-side paging](https://github.com/michaelbromley/ngx-pagination/tree/737cc1611ae3ceb7150e6aad5efed67b10ba0a54#server-side-paging) in the readme. Let me know if that addresses your use-case.

**Comment by arikbidny** [comment]
Hey , I saw it but in this case i need to pass only the amount or total , but I'm making the pagination on server side and what I'm passing to front its count, next ( url string ) and previous ( url string ) 
Can I feet your code to this pattern ? 
again thanks for your help .

**Comment by michaelbromley** [comment]
I don't quite understand what you are describing here. Could you provide some code examples and the format of data returned by your backend?

**Comment by arikbidny** [comment]
{count: 7, next: null, previous: null, results: Array(7)}
count: 7
next: null
previous:null
results: (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
__proto__: Object


Its the response from my django rest api backend .

**Comment by michaelbromley** [comment]
Does the backend not return the total number of items in the collection?

**Comment by michaelbromley** [comment]
When I say "total number of items in the collection", I mean the total unpaginated count, rather than the total for a single page. So if you have 1000 users and the server returns 10 per page, the total items is 1000.

Without knowing the total items, it is not possible to generate pagination links, since we would have no way to know how many pages there actually are.

If your backend only returns "next page or null", and does not have the ability to return the total number items, then unfortunately you won't be able to use this library to generate your pagination. 

I don't know anything about the Django Rest Framework, but looking the the docs here (http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination) the examples show a `count` property which seems to contain the total items count.

**Comment by arikbidny** [comment]
I'm getting the total count of all items in count variable ...

**Comment by michaelbromley** [comment]
Ah okay. From your original comment before the edit, I thought you just received the number of items in the current page.

In that case, the docs link I gave in my first reply should stand. Also see the demo here: http://michaelbromley.github.io/ngx-pagination/#/server-paging

If you are still having trouble, please post what you have tried so far.
