### ISSUE TITLE
How to remove the restriction of output information using pagination?

### ISSUE THREAD

**Issue by EarphoneWeb** [michaelbromley/ngx-pagination#273]
Angular version: ^4.4.6

ngx-pagination version: ^3.2.0

How to properly install the pagination to request each page on the server? At the moment, I need to assign a value of totalItem to display the pagination. Well, when I do so that the pages are taken from the server, the pagination just disappears.

html:
```
<div *ngFor="let post of posts | paginate: {itemsPerPage: 10, currentPage:page, id: 'server', totalItems: posts?.length}"> 
....
</div>
<div class="pagination-block " style="justify-content: center">
  <pagination-controls (pageChange)="getPosts($event)" id="server">
  </pagination-controls>
</div> 
```
ts:
```
  page: number;

  ngOnInit() {
    this.getPosts(this.page);
  }

  getPosts(page: number) {
    this.page = page;
    this.servPost.getPosts(page).subscribe(
      (data: Post[]) => {
        this.posts = data; 
    });
  }

```
service:
```
    page: number = 1;
      
    getPosts(page?: number): Observable<Post[]>{
        return this._authService.get(`posts?page=${page}`)
        .map((res: Response) => <Post[]>res.json())
            .do(res => {
                this.page = page;
            })
    }
```

**Comment by michaelbromley** [comment]
Hi,

When paging is done on the server, the server response should also include the total number of items in the whole (un-paged) collection. The way this data is exposed depends on the backend, but it is quite common to have a `count` or `totalItems` property returned in the JSON response.

Currently, you are setting the "totalItems" value to be equal to the number of items on the current page. In such a case, the pagination is not displayed because it is deemed to be unnecessary.

For examples in practice, see [the demo app](http://michaelbromley.github.io/ngx-pagination/#/server-paging) and also the [docs on server-side paging](https://github.com/michaelbromley/ngx-pagination#server-side-paging).
