### ISSUE TITLE
Can anyone help to include ngx-pagination inside ngx-datatable footer component?

### ISSUE THREAD

**Issue by swathiraok** [michaelbromley/ngx-pagination#282]

**Comment by michaelbromley** [comment]
Hi,

This is more of a support request rather than an issue. At the very minimum, you should describe what you have tried already and what the result was. Best would be to put together a reproduction - as is advised in the issue template.

Otherwise you are just asking me or someone else to do all the work for you, which is not a sustainable way to run an open source project for me!

Feel free to add some more detail and I'll see if I can help.
