### ISSUE TITLE
How can i set the id that comes from @input from another component

### ISSUE THREAD

**Issue by elninotorres** [michaelbromley/ngx-pagination#284]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```
providing id like this is not working
id: '{{title}}' where title is @input property
```

**Comment by michaelbromley** [comment]
That's because it would be interpreted as a string literal "{{title}}". If this is the argument being passed to the pipe, then just `id: title` should work. If you are binding to the pagination controls, then `[id]="title"`.

Review the [template syntax](https://angular.io/guide/template-syntax) section of the Angular docs.

**Comment by elninotorres** [comment]
Thank You, It is Working Now, My problem was i did not enclose id in square brackets.Now i got my error
