### ISSUE TITLE
why |pagination ?

### ISSUE THREAD

**Issue by phil123456** [michaelbromley/ngx-pagination#369]
the whole idea is to provide  pagination  to the server
not to fetch all the data and use a pipe to paginate them

the component does not display anything if I dont use the pipe

this is just useless

**Comment by michaelbromley** [comment]
Please fill out the issue template, or close the issue if there is no specific bug to report.

**Comment by oza75** [comment]
Thanks @phil123456 
The role of a pagination component is to display only links that will be used to navigate between pages.
It is a bad idea to retrieve all the data at once and then paginate page by page.
If the maintainers of this package can give us more explanation it will help us to understand their logic otherwise this component is very very useless

**Comment by michaelbromley** [comment]
Just gonna leave this link to the relevant readme section here: https://github.com/michaelbromley/ngx-pagination#server-side-paging

Next time you consider labeling a project "useless", please take the time to actually understand what you are talking about first.
